### ISSUE TITLE
Switch module bundler to rollup

### ISSUE THREAD

**Issue by doodlewind** [MuYunyun/diana#2]
Both react and vue has migrated to [rollup](https://github.com/rollup/rollup) as module bundler for these reasons:

* Neater output format with tree shaking optimization.
* Multi output standards support (ES module / umd / commonJS).
* Simpler config.
* Faster speed.

For pure JavaScript project, rollup seems to be a better solution. Any ideas migrating?

**Comment by MuYunyun** [comment]
@doodlewind Thanks for the advice you gave, it sounds great and I might use it for refactoring in the future. Thanks again.

**Comment by MuYunyun** [comment]
This month prepare to migrate. [rollup](https://rollupjs.org/guide/en)
